name: CI

on: [push]

env:
  # 2026 zaman uyuşmazlığı ve SSL hatalarını aşmak için
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  # Node.js 24 kullanımını zorunlu kılar
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  # Shopify CLI'ın robotu (GitHub Actions) otomatik tanıması için
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOP_PASSWORD }}

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Lighthouse CI on Shopify theme
        uses: Shopify/lighthouse-ci-action@v1.4.0
        with:
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}

  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Shopify Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}
